<template>
  <UAlert
    :title="$tt('$.eshop.construction.title')"
    :description="$tt('$.eshop.construction.description')"
    color="warning"
    variant="soft"
    icon="i-lucide-construction"
  />
</template>
